### ISSUE TITLE
App not working

### ISSUE THREAD

**Issue by amyfeder** [aculligan/Zendesk_Priority_Highlights#6] opened 2019-02-28 14:51 UTC
We have over 20 people using this app and it hasn't been working for everyone since at least the beginning of the year. I have removed all other extensions to see if that helps and it has not.

**Comment by aculligan** [comment] 2019-06-22 01:34
This is a duplicate of #2. Fixed as of 2019-06-21. Sorry it took so long. Zendesk keeps changing the selectors and I keep coming up with workarounds. Can't promise it'll work for long, but please let me know if you have more issues.

**Closed by aculligan** 2019-06-22 01:34 UTC
Labels: bug, duplicate, fixed
